# -*- coding: utf-8 -*-
"""
Bank soal UAS Manajemen Keuangan Bisnis - Pertemuan 9-14.
Sumber: RPS_Manajemen_Keuangan_Bisnis.docx, Ardiansyah Japlani, S.E., M.B.A.
Program Studi S1 Kewirausahaan, FEB Universitas Muhammadiyah Metro.

Cakupan: Penganggaran Modal, Metode Penilaian Investasi (NPV/IRR/Payback/PI),
Manajemen Modal Kerja, Manajemen Kas-Piutang-Persediaan, Sumber Pembiayaan,
Penilaian Saham & Obligasi.

Total 200 soal. Tiap mahasiswa (dari 21 mahasiswa) menerima 20 soal acak
berdasarkan NPM; opsi jawaban diacak ulang per NPM.
Soal konsep ditulis manual; soal hitung dibangkitkan dan diverifikasi Python.
"""

DURASI_UAS_MENIT = 15
JUMLAH_SOAL_PER_MAHASISWA = 20
JUMLAH_MAHASISWA = 21
ACAK_OPSI = True

UAS_BANK = [
    {"q": "Penganggaran modal (capital budgeting) adalah proses...", "o": ["Mengevaluasi dan memilih investasi jangka panjang", "Mencatat transaksi harian", "Menyusun gaji karyawan", "Membuat iklan"], "a": 0},
    {"q": "Keputusan penganggaran modal penting karena...", "o": ["Melibatkan dana besar, jangka panjang, dan sulit dibatalkan", "Bernilai kecil dan mudah dibatalkan", "Tidak berdampak pada arus kas", "Hanya urusan pemasaran"], "a": 0},
    {"q": "Contoh proyek investasi dalam capital budgeting adalah...", "o": ["Pembelian mesin baru atau ekspansi pabrik", "Pembayaran listrik bulanan", "Pembelian alat tulis", "Pembayaran gaji harian"], "a": 0},
    {"q": "Dalam manajemen keuangan, keputusan capital budgeting termasuk...", "o": ["Keputusan investasi", "Keputusan dividen", "Keputusan pembiayaan jangka pendek", "Keputusan penggajian"], "a": 0},
    {"q": "Tiga keputusan utama manajer keuangan adalah...", "o": ["Investasi, pembiayaan, dan dividen", "Produksi, pemasaran, dan SDM", "Iklan, promosi, dan diskon", "Beli, jual, dan simpan"], "a": 0},
    {"q": "Jenis proyek investasi berdasarkan tujuannya antara lain...", "o": ["Ekspansi, penggantian, dan proyek wajib (mandatory)", "Merah, kuning, hijau", "Kecil, sedang, besar", "Pagi, siang, malam"], "a": 0},
    {"q": "Investasi jangka panjang menuntut analisis cermat karena...", "o": ["Kesalahan sulit diperbaiki dan berdampak lama", "Mudah dibatalkan kapan saja", "Tidak memakai dana", "Tidak berisiko"], "a": 0},
    {"q": "Tujuan utama keputusan investasi modal adalah...", "o": ["Memaksimalkan nilai perusahaan", "Menghabiskan kas", "Menambah utang tanpa tujuan", "Mengurangi laba"], "a": 0},
    {"q": "Arus kas yang relevan dalam capital budgeting adalah...", "o": ["Arus kas inkremental akibat proyek", "Laba akuntansi masa lalu", "Biaya tenggelam (sunk cost)", "Beban penyusutan saja"], "a": 0},
    {"q": "Biaya tenggelam (sunk cost) dalam evaluasi proyek sebaiknya...", "o": ["Diabaikan karena tidak dapat diubah", "Selalu dimasukkan", "Dijadikan dasar utama", "Ditambah ke arus kas"], "a": 0},
    {"q": "Manajer keuangan menilai kelayakan proyek terutama dari...", "o": ["Arus kas yang dihasilkan proyek", "Warna logo perusahaan", "Jumlah karyawan", "Lokasi kantor"], "a": 0},
    {"q": "Keputusan investasi jangka panjang berkaitan langsung dengan...", "o": ["Aktiva tetap dan proyek strategis", "Kas kecil harian", "Pembelian ATK", "Gaji mingguan"], "a": 0},
    {"q": "Dalam kewirausahaan, capital budgeting membantu wirausaha...", "o": ["Memutuskan investasi alat/usaha yang menguntungkan", "Menghindari semua investasi", "Mengabaikan arus kas", "Menambah biaya tanpa manfaat"], "a": 0},
    {"q": "Salah satu jenis proyek mandatory (wajib) adalah...", "o": ["Investasi untuk memenuhi regulasi keselamatan", "Ekspansi pasar baru", "Penggantian mesin usang", "Pembelian saham"], "a": 0},
    {"q": "Net Present Value (NPV) mengukur...", "o": ["Selisih nilai sekarang arus kas masuk dan investasi awal", "Laba akuntansi tahunan", "Jumlah unit terjual", "Rasio lancar"], "a": 0},
    {"q": "Kaidah keputusan NPV adalah menerima proyek bila...", "o": ["NPV positif", "NPV negatif", "NPV nol", "IRR negatif"], "a": 0},
    {"q": "Internal Rate of Return (IRR) adalah...", "o": ["Tingkat diskonto yang membuat NPV sama dengan nol", "Selisih kas masuk dan keluar", "Rasio lancar", "Laba bersih"], "a": 0},
    {"q": "Kaidah keputusan IRR adalah menerima proyek bila...", "o": ["IRR lebih besar dari biaya modal", "IRR lebih kecil dari biaya modal", "IRR nol", "IRR negatif"], "a": 0},
    {"q": "Payback Period mengukur...", "o": ["Lama waktu pengembalian investasi dari arus kas", "Nilai sekarang arus kas", "Tingkat imbal hasil", "Rasio utang"], "a": 0},
    {"q": "Profitability Index (PI) dihitung dengan...", "o": ["Nilai sekarang arus kas dibagi investasi awal", "Investasi dibagi laba", "Arus kas dikurangi investasi", "Laba dibagi penjualan"], "a": 0},
    {"q": "Kaidah keputusan Profitability Index adalah menerima proyek bila...", "o": ["PI lebih dari 1", "PI kurang dari 1", "PI nol", "PI negatif"], "a": 0},
    {"q": "Kelemahan utama metode Payback Period adalah...", "o": ["Mengabaikan nilai waktu uang dan arus kas setelah periode balik modal", "Terlalu rumit", "Selalu salah", "Memakai diskonto ganda"], "a": 0},
    {"q": "Metode yang paling dianjurkan karena mempertimbangkan nilai waktu uang adalah...", "o": ["Net Present Value", "Payback Period sederhana", "Accounting Rate of Return", "Tebakan"], "a": 0},
    {"q": "Bila NPV positif maka IRR proyek...", "o": ["Lebih besar dari biaya modal", "Lebih kecil dari biaya modal", "Selalu nol", "Selalu negatif"], "a": 0},
    {"q": "Dua proyek saling meniadakan (mutually exclusive) sebaiknya dipilih berdasarkan...", "o": ["NPV tertinggi", "Payback terpanjang", "Investasi terbesar", "Nama proyek"], "a": 0},
    {"q": "Discounted Payback Period berbeda dari Payback biasa karena...", "o": ["Memperhitungkan nilai waktu uang", "Mengabaikan arus kas", "Tidak memakai diskonto", "Menghitung laba"], "a": 0},
    {"q": "Semakin tinggi NPV suatu proyek, maka...", "o": ["Semakin besar tambahan nilai bagi perusahaan", "Semakin rugi", "Semakin tidak layak", "Tidak berpengaruh"], "a": 0},
    {"q": "IRR dinyatakan dalam bentuk...", "o": ["Persentase", "Rupiah", "Unit", "Tahun"], "a": 0},
    {"q": "Modal kerja bersih (net working capital) dihitung dari...", "o": ["Aktiva lancar dikurangi kewajiban lancar", "Aktiva tetap dikurangi utang", "Penjualan dikurangi biaya", "Kas ditambah piutang"], "a": 0},
    {"q": "Modal kerja kotor (gross working capital) mengacu pada...", "o": ["Total aktiva lancar", "Aktiva lancar dikurangi kewajiban lancar", "Total utang", "Ekuitas"], "a": 0},
    {"q": "Siklus konversi kas (cash conversion cycle) menunjukkan...", "o": ["Waktu dari pengeluaran kas untuk bahan hingga penerimaan kas dari penjualan", "Umur mesin", "Lama proyek investasi", "Masa jatuh tempo obligasi"], "a": 0},
    {"q": "Komponen siklus konversi kas meliputi...", "o": ["Periode persediaan + periode piutang - periode utang", "Kas + piutang + persediaan", "Utang + ekuitas", "Penjualan - biaya"], "a": 0},
    {"q": "Kebijakan modal kerja agresif ditandai dengan...", "o": ["Aktiva lancar rendah, mengejar profitabilitas dengan risiko likuiditas lebih tinggi", "Aktiva lancar sangat tinggi", "Tanpa risiko", "Kas berlebih selalu"], "a": 0},
    {"q": "Kebijakan modal kerja konservatif ditandai dengan...", "o": ["Aktiva lancar tinggi, likuiditas aman tetapi profitabilitas lebih rendah", "Aktiva lancar minimum", "Utang jangka pendek maksimum", "Tanpa kas"], "a": 0},
    {"q": "Modal kerja permanen adalah...", "o": ["Modal kerja minimum yang selalu dibutuhkan usaha", "Modal kerja musiman", "Utang jangka panjang", "Aktiva tetap"], "a": 0},
    {"q": "Tujuan manajemen modal kerja adalah...", "o": ["Menyeimbangkan likuiditas dan profitabilitas", "Memaksimalkan utang", "Menghabiskan kas", "Menambah persediaan tanpa batas"], "a": 0},
    {"q": "Semakin pendek siklus konversi kas, umumnya...", "o": ["Semakin baik karena kas lebih cepat kembali", "Semakin buruk", "Tidak berpengaruh", "Semakin rugi"], "a": 0},
    {"q": "Modal kerja yang terlalu besar dapat menyebabkan...", "o": ["Dana menganggur dan profitabilitas menurun", "Kebangkrutan seketika", "Likuiditas hilang", "Utang membengkak"], "a": 0},
    {"q": "Modal kerja yang terlalu kecil berisiko...", "o": ["Kesulitan likuiditas dan gagal memenuhi kewajiban", "Laba berlebih", "Kas menumpuk", "Tidak ada risiko"], "a": 0},
    {"q": "Aktiva lancar mencakup...", "o": ["Kas, piutang, dan persediaan", "Mesin dan gedung", "Utang jangka panjang", "Modal saham"], "a": 0},
    {"q": "Kewajiban lancar mencakup...", "o": ["Utang dagang dan utang jangka pendek", "Obligasi 10 tahun", "Modal saham", "Aktiva tetap"], "a": 0},
    {"q": "Manajemen modal kerja berfokus pada...", "o": ["Pengelolaan aktiva lancar dan kewajiban lancar", "Investasi mesin jangka panjang", "Penerbitan saham", "Pembagian dividen"], "a": 0},
    {"q": "Tiga motif memegang kas menurut teori adalah...", "o": ["Transaksi, berjaga-jaga, dan spekulasi", "Beli, jual, simpan", "Iklan, promosi, diskon", "Pagi, siang, malam"], "a": 0},
    {"q": "Tujuan manajemen kas adalah...", "o": ["Menjaga likuiditas sekaligus meminimalkan kas menganggur", "Menumpuk kas sebanyak mungkin", "Menghabiskan kas", "Menghindari transaksi"], "a": 0},
    {"q": "Manajemen piutang berkaitan dengan...", "o": ["Kebijakan kredit dan penagihan penjualan kredit", "Pembelian mesin", "Penerbitan obligasi", "Pembagian dividen"], "a": 0},
    {"q": "Tujuan manajemen persediaan adalah...", "o": ["Menjaga ketersediaan barang dengan biaya seminimal mungkin", "Menumpuk stok tanpa batas", "Menghapus persediaan", "Menaikkan biaya simpan"], "a": 0},
    {"q": "Economic Order Quantity (EOQ) menentukan...", "o": ["Jumlah pemesanan optimal yang meminimalkan biaya persediaan", "Harga jual produk", "Tarif pajak", "Gaji karyawan"], "a": 0},
    {"q": "Kebijakan kredit yang terlalu longgar berisiko...", "o": ["Meningkatkan piutang tak tertagih", "Menurunkan penjualan", "Menghapus piutang", "Menambah kas seketika"], "a": 0},
    {"q": "Manajemen kas yang baik menjaga keseimbangan antara...", "o": ["Likuiditas dan profitabilitas", "Iklan dan promosi", "Produksi dan gudang", "Pajak dan gaji"], "a": 0},
    {"q": "Mempercepat penagihan piutang akan...", "o": ["Mempercepat arus kas masuk", "Memperlambat kas", "Menambah utang", "Menurunkan penjualan"], "a": 0},
    {"q": "Biaya persediaan mencakup...", "o": ["Biaya pemesanan dan biaya penyimpanan", "Biaya iklan dan promosi", "Biaya dividen", "Biaya bunga obligasi"], "a": 0},
    {"q": "Kas yang menganggur sebaiknya...", "o": ["Diinvestasikan pada instrumen jangka pendek yang likuid", "Dibiarkan tanpa hasil", "Dibakar", "Disembunyikan"], "a": 0},
    {"q": "Manajemen piutang bertujuan...", "o": ["Memaksimalkan penjualan kredit dengan risiko tertagih terkendali", "Menghapus penjualan kredit", "Menaikkan bad debt", "Menghindari pelanggan"], "a": 0},
    {"q": "Persediaan yang berlebihan menimbulkan...", "o": ["Biaya penyimpanan tinggi dan risiko kerusakan", "Kas berlebih", "Penjualan otomatis", "Laba pasti"], "a": 0},
    {"q": "Motif berjaga-jaga memegang kas bertujuan...", "o": ["Mengantisipasi kebutuhan tak terduga", "Berspekulasi harga", "Transaksi rutin", "Membayar dividen"], "a": 0},
    {"q": "Manajemen kas, piutang, dan persediaan merupakan bagian dari...", "o": ["Manajemen modal kerja", "Penganggaran modal", "Penilaian obligasi", "Kebijakan dividen"], "a": 0},
    {"q": "Sumber pembiayaan jangka pendek contohnya...", "o": ["Utang dagang dan kredit bank jangka pendek", "Obligasi 10 tahun", "Saham biasa", "Laba ditahan jangka panjang"], "a": 0},
    {"q": "Sumber pembiayaan jangka panjang contohnya...", "o": ["Obligasi dan saham", "Utang dagang", "Kredit modal kerja harian", "Kas kecil"], "a": 0},
    {"q": "Pembiayaan melalui utang (debt) memiliki ciri...", "o": ["Ada kewajiban bunga tetap dan pokok", "Tanpa kewajiban apa pun", "Memberi hak suara penuh", "Tidak berisiko"], "a": 0},
    {"q": "Pembiayaan melalui ekuitas (equity) memiliki ciri...", "o": ["Tidak wajib membayar bunga tetapi berbagi kepemilikan", "Wajib bunga tetap", "Harus dilunasi tiap bulan", "Tanpa risiko dilusi"], "a": 0},
    {"q": "Biaya modal (cost of capital) adalah...", "o": ["Tingkat imbal hasil minimum yang harus dihasilkan investasi", "Total utang perusahaan", "Harga saham", "Jumlah dividen"], "a": 0},
    {"q": "Struktur modal optimal tercapai ketika...", "o": ["Biaya modal rata-rata tertimbang (WACC) minimum dan nilai perusahaan maksimum", "Utang 100 persen", "Ekuitas 100 persen", "WACC maksimum"], "a": 0},
    {"q": "WACC merupakan singkatan dari...", "o": ["Weighted Average Cost of Capital", "Working Asset Cash Cycle", "Weekly Average Credit Cost", "Wide Area Capital Control"], "a": 0},
    {"q": "Penggunaan utang yang berlebihan meningkatkan...", "o": ["Risiko keuangan (financial leverage) dan risiko gagal bayar", "Ekuitas otomatis", "Kas tanpa batas", "Laba pasti"], "a": 0},
    {"q": "Keunggulan pembiayaan utang adalah...", "o": ["Bunga dapat mengurangi pajak (tax shield)", "Tidak ada kewajiban", "Memberi kendali ke kreditur", "Tanpa risiko"], "a": 0},
    {"q": "Laba ditahan (retained earnings) termasuk sumber pembiayaan...", "o": ["Internal (dari dalam perusahaan)", "Eksternal utang", "Eksternal ekuitas baru", "Jangka sangat pendek"], "a": 0},
    {"q": "Semakin tinggi risiko yang ditanggung investor, maka imbal hasil yang diminta...", "o": ["Semakin tinggi", "Semakin rendah", "Tetap", "Nol"], "a": 0},
    {"q": "Trade-off dalam struktur modal adalah antara...", "o": ["Manfaat pajak utang dan risiko kebangkrutan", "Iklan dan promosi", "Kas dan piutang", "Produksi dan penjualan"], "a": 0},
    {"q": "Pembiayaan ekuitas melalui penjualan saham baru dapat menimbulkan...", "o": ["Dilusi kepemilikan pemegang saham lama", "Kewajiban bunga tetap", "Jatuh tempo pokok", "Pengurangan pajak"], "a": 0},
    {"q": "Sumber pembiayaan internal yang utama adalah...", "o": ["Laba ditahan", "Obligasi", "Kredit bank", "Saham baru"], "a": 0},
    {"q": "Saham preferen berbeda dari saham biasa karena...", "o": ["Memberi dividen tetap dan prioritas atas saham biasa", "Tidak memberi dividen", "Selalu berhak suara penuh", "Jatuh tempo seperti obligasi"], "a": 0},
    {"q": "Model Gordon (dividend growth) menilai harga saham dengan rumus...", "o": ["D1 dibagi (r - g)", "D1 dikali (r - g)", "(r - g) dibagi D1", "D1 ditambah r"], "a": 0},
    {"q": "Nilai sebuah obligasi sama dengan...", "o": ["Nilai sekarang kupon ditambah nilai sekarang nilai nominal", "Harga saham", "Total penjualan", "Laba bersih"], "a": 0},
    {"q": "Hubungan harga obligasi dan suku bunga pasar bersifat...", "o": ["Berkebalikan (suku bunga naik, harga turun)", "Searah", "Tidak berhubungan", "Selalu tetap"], "a": 0},
    {"q": "Current yield obligasi dihitung dari...", "o": ["Kupon tahunan dibagi harga pasar obligasi", "Harga dibagi kupon", "Nilai nominal dikali kupon", "Kupon dikurangi harga"], "a": 0},
    {"q": "Saham biasa memberikan pemiliknya...", "o": ["Hak suara dan klaim sisa atas laba (dividen tidak tetap)", "Dividen tetap dijamin", "Bunga tetap", "Jatuh tempo pokok"], "a": 0},
    {"q": "Obligasi yang dijual di atas nilai nominal disebut dijual pada...", "o": ["Premium", "Diskon", "Par", "Default"], "a": 0},
    {"q": "Obligasi yang dijual di bawah nilai nominal disebut dijual pada...", "o": ["Diskon", "Premium", "Par", "Yield"], "a": 0},
    {"q": "Yield to maturity (YTM) adalah...", "o": ["Imbal hasil total bila obligasi dipegang hingga jatuh tempo", "Kupon tahunan saja", "Harga beli obligasi", "Nilai nominal"], "a": 0},
    {"q": "Dalam model Gordon, syarat agar rumus valid adalah...", "o": ["Tingkat imbal hasil r lebih besar dari pertumbuhan g", "g lebih besar dari r", "r sama dengan g", "g negatif selalu"], "a": 0},
    {"q": "Dividen saham preferen umumnya bersifat...", "o": ["Tetap", "Tumbuh terus", "Nol", "Acak"], "a": 0},
    {"q": "Jika suku bunga pasar turun, harga obligasi akan...", "o": ["Naik", "Turun", "Tetap", "Nol"], "a": 0},
    {"q": "Penilaian saham dan obligasi pada dasarnya menghitung...", "o": ["Nilai sekarang arus kas masa depan", "Laba masa lalu", "Biaya produksi", "Jumlah karyawan"], "a": 0},
    {"q": "Klaim pemegang obligasi terhadap perusahaan bersifat...", "o": ["Lebih diutamakan daripada pemegang saham", "Paling akhir", "Sama dengan saham biasa", "Tidak ada"], "a": 0},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp40 juta per tahun. Payback Period proyek adalah...", "o": ["4 tahun", "0.4 tahun", "1.8 tahun", "2.5 tahun"], "a": 3},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp60 juta per tahun. Payback Period proyek adalah...", "o": ["3.33 tahun", "0.3 tahun", "4.83 tahun", "2.63 tahun"], "a": 0},
    {"q": "Investasi Rp120 juta menghasilkan arus kas Rp25 juta per tahun. Payback Period proyek adalah...", "o": ["6.3 tahun", "0.21 tahun", "4.1 tahun", "4.8 tahun"], "a": 3},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["1.3 tahun", "0.5 tahun", "3.5 tahun", "2 tahun"], "a": 3},
    {"q": "Investasi Rp150 juta menghasilkan arus kas Rp30 juta per tahun. Payback Period proyek adalah...", "o": ["5 tahun", "6.5 tahun", "0.2 tahun", "4.3 tahun"], "a": 0},
    {"q": "Investasi Rp150 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["2.3 tahun", "0.33 tahun", "4.5 tahun", "3 tahun"], "a": 3},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp60 juta per tahun. Payback Period proyek adalah...", "o": ["1.67 tahun", "0.97 tahun", "0.6 tahun", "3.17 tahun"], "a": 0},
    {"q": "Investasi Rp120 juta menghasilkan arus kas Rp60 juta per tahun. Payback Period proyek adalah...", "o": ["1.3 tahun", "0.5 tahun", "2 tahun", "3.5 tahun"], "a": 2},
    {"q": "Investasi Rp180 juta menghasilkan arus kas Rp60 juta per tahun. Payback Period proyek adalah...", "o": ["0.33 tahun", "3 tahun", "4.5 tahun", "2.3 tahun"], "a": 1},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp30 juta per tahun. Payback Period proyek adalah...", "o": ["5.97 tahun", "8.17 tahun", "6.67 tahun", "0.15 tahun"], "a": 2},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["5.5 tahun", "0.25 tahun", "4 tahun", "3.3 tahun"], "a": 2},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp40 juta per tahun. Payback Period proyek adalah...", "o": ["5 tahun", "0.2 tahun", "6.5 tahun", "4.3 tahun"], "a": 0},
    {"q": "Investasi Rp120 juta menghasilkan arus kas Rp40 juta per tahun. Payback Period proyek adalah...", "o": ["0.33 tahun", "2.3 tahun", "3 tahun", "4.5 tahun"], "a": 2},
    {"q": "Investasi Rp150 juta menghasilkan arus kas Rp40 juta per tahun. Payback Period proyek adalah...", "o": ["5.25 tahun", "0.27 tahun", "3.75 tahun", "3.05 tahun"], "a": 2},
    {"q": "Investasi Rp180 juta menghasilkan arus kas Rp25 juta per tahun. Payback Period proyek adalah...", "o": ["7.2 tahun", "6.5 tahun", "0.14 tahun", "8.7 tahun"], "a": 0},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp30 juta per tahun. Payback Period proyek adalah...", "o": ["4.83 tahun", "0.3 tahun", "3.33 tahun", "2.63 tahun"], "a": 2},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp35 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV negatif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan", "Ditolak karena NPV negatif"], "a": 3},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp35 juta per tahun selama 5 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV positif", "Ditolak karena NPV positif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan"], "a": 0},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp35 juta per tahun selama 4 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditunda tanpa alasan", "Ditolak karena NPV negatif", "Diterima tanpa perhitungan", "Diterima karena NPV negatif"], "a": 1},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp70 juta per tahun selama 3 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp10 juta", "Rp-61.87 juta", "Rp-31.87 juta", "Rp8.13 juta"], "a": 2},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp60 juta per tahun selama 3 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp-20 juta", "Rp-80.79 juta", "Rp-10.79 juta", "Rp-50.79 juta"], "a": 3},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp50 juta per tahun selama 5 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima tanpa perhitungan", "Ditolak karena NPV positif", "Ditunda tanpa alasan", "Diterima karena NPV positif"], "a": 3},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp50 juta per tahun selama 4 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima tanpa perhitungan", "Diterima karena NPV positif", "Ditolak karena NPV positif", "Ditunda tanpa alasan"], "a": 1},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp70 juta per tahun selama 5 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp127.36 juta", "Rp145.36 juta", "Rp169.36 juta", "Rp230 juta"], "a": 1},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp70 juta per tahun selama 4 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp106.89 juta", "Rp180 juta", "Rp121.89 juta", "Rp141.89 juta"], "a": 2},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp40 juta per tahun selama 4 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp-103.21 juta", "Rp-73.21 juta", "Rp-40 juta", "Rp-33.21 juta"], "a": 1},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp40 juta per tahun selama 4 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp40 juta", "Rp25.49 juta", "Rp1.49 juta", "Rp-16.51 juta"], "a": 2},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp40 juta per tahun selama 4 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp-23.21 juta", "Rp10 juta", "Rp6.79 juta", "Rp-45.71 juta"], "a": 0},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp40 juta per tahun selama 4 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp-38.51 juta", "Rp-108.51 juta", "Rp-78.51 juta", "Rp-40 juta"], "a": 2},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp35 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV negatif", "Ditolak karena NPV negatif", "Diterima tanpa perhitungan", "Ditunda tanpa alasan"], "a": 1},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp50 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima tanpa perhitungan", "Ditunda tanpa alasan", "Diterima karena NPV positif", "Ditolak karena NPV positif"], "a": 2},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp70 juta per tahun selama 4 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima tanpa perhitungan", "Ditunda tanpa alasan", "Diterima karena NPV positif", "Ditolak karena NPV positif"], "a": 2},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp60 juta per tahun selama 3 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV positif", "Diterima karena NPV positif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan"], "a": 1},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp70 juta per tahun selama 4 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditunda tanpa alasan", "Diterima tanpa perhitungan", "Ditolak karena NPV positif", "Diterima karena NPV positif"], "a": 3},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp50 juta per tahun selama 4 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp20.49 juta", "Rp38.49 juta", "Rp62.49 juta", "Rp80 juta"], "a": 1},
    {"q": "Proyek investasi Rp100 juta, arus kas Rp35 juta per tahun selama 3 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp-27.96 juta", "Rp7.04 juta", "Rp5 juta", "Rp-12.96 juta"], "a": 3},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp60 juta per tahun selama 5 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV positif", "Diterima karena NPV positif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan"], "a": 1},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp60 juta per tahun selama 5 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV positif", "Ditunda tanpa alasan", "Ditolak karena NPV positif", "Diterima tanpa perhitungan"], "a": 0},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp35 juta per tahun selama 5 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV negatif", "Diterima karena NPV negatif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan"], "a": 0},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp35 juta per tahun selama 4 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp-66.19 juta", "Rp-13.69 juta", "Rp-10 juta", "Rp-43.69 juta"], "a": 3},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp70 juta per tahun selama 3 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp78.08 juta", "Rp90 juta", "Rp36.08 juta", "Rp54.08 juta"], "a": 3},
    {"q": "Proyek investasi Rp120 juta, arus kas Rp70 juta per tahun selama 4 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp92.61 juta", "Rp160 juta", "Rp74.61 juta", "Rp116.61 juta"], "a": 0},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp60 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditunda tanpa alasan", "Diterima tanpa perhitungan", "Ditolak karena NPV negatif", "Diterima karena NPV negatif"], "a": 2},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp50 juta per tahun selama 3 tahun, biaya modal 10 persen. NPV proyek mendekati...", "o": ["Rp-75.66 juta", "Rp-35.66 juta", "Rp-105.66 juta", "Rp-50 juta"], "a": 0},
    {"q": "Proyek investasi Rp200 juta, arus kas Rp50 juta per tahun selama 4 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV negatif", "Diterima tanpa perhitungan", "Ditunda tanpa alasan", "Ditolak karena NPV negatif"], "a": 3},
    {"q": "Proyek investasi Rp150 juta, arus kas Rp50 juta per tahun selama 5 tahun, biaya modal 12 persen. NPV proyek mendekati...", "o": ["Rp60.24 juta", "Rp7.74 juta", "Rp100 juta", "Rp30.24 juta"], "a": 3},
    {"q": "Nilai sekarang arus kas Rp170 juta, investasi Rp200 juta. Berdasarkan Profitability Index, proyek...", "o": ["Tidak layak karena PI kurang dari 1", "Selalu ditolak", "Layak tanpa perhitungan", "Layak karena PI kurang dari 1"], "a": 0},
    {"q": "Nilai sekarang arus kas Rp135 juta, investasi Rp150 juta. Berdasarkan Profitability Index, proyek...", "o": ["Selalu ditolak", "Tidak layak karena PI kurang dari 1", "Layak karena PI kurang dari 1", "Layak tanpa perhitungan"], "a": 1},
    {"q": "Nilai sekarang arus kas proyek Rp165 juta dan investasi awal Rp150 juta. Profitability Index adalah...", "o": ["1.1", "0.91", "1.4", "0.85"], "a": 0},
    {"q": "Nilai sekarang arus kas proyek Rp135 juta dan investasi awal Rp150 juta. Profitability Index adalah...", "o": ["1.2", "1.11", "0.9", "0.65"], "a": 2},
    {"q": "Nilai sekarang arus kas Rp115 juta, investasi Rp100 juta. Berdasarkan Profitability Index, proyek...", "o": ["Tidak layak karena PI lebih dari 1", "Layak tanpa perhitungan", "Layak karena PI lebih dari 1", "Selalu ditolak"], "a": 2},
    {"q": "Nilai sekarang arus kas proyek Rp115 juta dan investasi awal Rp100 juta. Profitability Index adalah...", "o": ["0.87", "0.9", "1.15", "1.45"], "a": 2},
    {"q": "Nilai sekarang arus kas proyek Rp145 juta dan investasi awal Rp100 juta. Profitability Index adalah...", "o": ["0.69", "1.45", "1.2", "1.75"], "a": 1},
    {"q": "Nilai sekarang arus kas Rp230 juta, investasi Rp200 juta. Berdasarkan Profitability Index, proyek...", "o": ["Selalu ditolak", "Layak karena PI lebih dari 1", "Layak tanpa perhitungan", "Tidak layak karena PI lebih dari 1"], "a": 1},
    {"q": "Nilai sekarang arus kas Rp85 juta, investasi Rp100 juta. Berdasarkan Profitability Index, proyek...", "o": ["Tidak layak karena PI kurang dari 1", "Layak karena PI kurang dari 1", "Selalu ditolak", "Layak tanpa perhitungan"], "a": 0},
    {"q": "Nilai sekarang arus kas Rp120 juta, investasi Rp150 juta. Berdasarkan Profitability Index, proyek...", "o": ["Layak tanpa perhitungan", "Selalu ditolak", "Tidak layak karena PI kurang dari 1", "Layak karena PI kurang dari 1"], "a": 2},
    {"q": "Nilai sekarang arus kas proyek Rp195 juta dan investasi awal Rp150 juta. Profitability Index adalah...", "o": ["1.6", "1.3", "1.05", "0.77"], "a": 1},
    {"q": "Nilai sekarang arus kas Rp145 juta, investasi Rp100 juta. Berdasarkan Profitability Index, proyek...", "o": ["Layak tanpa perhitungan", "Layak karena PI lebih dari 1", "Tidak layak karena PI lebih dari 1", "Selalu ditolak"], "a": 1},
    {"q": "Nilai sekarang arus kas proyek Rp85 juta dan investasi awal Rp100 juta. Profitability Index adalah...", "o": ["0.6", "1.15", "0.85", "1.18"], "a": 2},
    {"q": "Nilai sekarang arus kas Rp90 juta, investasi Rp120 juta. Berdasarkan Profitability Index, proyek...", "o": ["Layak karena PI kurang dari 1", "Layak tanpa perhitungan", "Tidak layak karena PI kurang dari 1", "Selalu ditolak"], "a": 2},
    {"q": "Nilai sekarang arus kas Rp215 juta, investasi Rp200 juta. Berdasarkan Profitability Index, proyek...", "o": ["Selalu ditolak", "Layak tanpa perhitungan", "Tidak layak karena PI lebih dari 1", "Layak karena PI lebih dari 1"], "a": 3},
    {"q": "Aktiva lancar perusahaan Rp148 juta dan kewajiban lancar Rp40 juta. Modal kerja bersih adalah...", "o": ["Rp-108 juta", "Rp188 juta", "Rp148 juta", "Rp108 juta"], "a": 3},
    {"q": "Aktiva lancar perusahaan Rp139 juta dan kewajiban lancar Rp63 juta. Modal kerja bersih adalah...", "o": ["Rp-76 juta", "Rp139 juta", "Rp76 juta", "Rp202 juta"], "a": 2},
    {"q": "Aktiva lancar perusahaan Rp170 juta dan kewajiban lancar Rp94 juta. Modal kerja bersih adalah...", "o": ["Rp76 juta", "Rp170 juta", "Rp264 juta", "Rp-76 juta"], "a": 0},
    {"q": "Aktiva lancar perusahaan Rp163 juta dan kewajiban lancar Rp70 juta. Modal kerja bersih adalah...", "o": ["Rp-93 juta", "Rp163 juta", "Rp93 juta", "Rp233 juta"], "a": 2},
    {"q": "Aktiva lancar perusahaan Rp116 juta dan kewajiban lancar Rp140 juta. Modal kerja bersih adalah...", "o": ["Rp-24 juta", "Rp116 juta", "Rp256 juta", "Rp24 juta"], "a": 0},
    {"q": "Aktiva lancar perusahaan Rp157 juta dan kewajiban lancar Rp57 juta. Modal kerja bersih adalah...", "o": ["Rp-100 juta", "Rp100 juta", "Rp157 juta", "Rp214 juta"], "a": 1},
    {"q": "Aktiva lancar perusahaan Rp170 juta dan kewajiban lancar Rp64 juta. Modal kerja bersih adalah...", "o": ["Rp170 juta", "Rp234 juta", "Rp106 juta", "Rp-106 juta"], "a": 2},
    {"q": "Aktiva lancar perusahaan Rp128 juta dan kewajiban lancar Rp137 juta. Modal kerja bersih adalah...", "o": ["Rp9 juta", "Rp-9 juta", "Rp265 juta", "Rp128 juta"], "a": 1},
    {"q": "Aktiva lancar perusahaan Rp199 juta dan kewajiban lancar Rp110 juta. Modal kerja bersih adalah...", "o": ["Rp199 juta", "Rp309 juta", "Rp89 juta", "Rp-89 juta"], "a": 2},
    {"q": "Aktiva lancar perusahaan Rp96 juta dan kewajiban lancar Rp101 juta. Modal kerja bersih adalah...", "o": ["Rp96 juta", "Rp5 juta", "Rp197 juta", "Rp-5 juta"], "a": 3},
    {"q": "Aktiva lancar perusahaan Rp177 juta dan kewajiban lancar Rp111 juta. Modal kerja bersih adalah...", "o": ["Rp-66 juta", "Rp66 juta", "Rp288 juta", "Rp177 juta"], "a": 1},
    {"q": "Aktiva lancar perusahaan Rp200 juta dan kewajiban lancar Rp121 juta. Modal kerja bersih adalah...", "o": ["Rp79 juta", "Rp321 juta", "Rp200 juta", "Rp-79 juta"], "a": 0},
    {"q": "Aktiva lancar perusahaan Rp146 juta dan kewajiban lancar Rp42 juta. Modal kerja bersih adalah...", "o": ["Rp188 juta", "Rp104 juta", "Rp-104 juta", "Rp146 juta"], "a": 1},
    {"q": "Aktiva lancar perusahaan Rp168 juta dan kewajiban lancar Rp75 juta. Modal kerja bersih adalah...", "o": ["Rp168 juta", "Rp243 juta", "Rp93 juta", "Rp-93 juta"], "a": 2},
    {"q": "Aktiva lancar perusahaan Rp104 juta dan kewajiban lancar Rp31 juta. Modal kerja bersih adalah...", "o": ["Rp73 juta", "Rp135 juta", "Rp104 juta", "Rp-73 juta"], "a": 0},
    {"q": "Periode persediaan 38 hari, periode penagihan piutang 41 hari, periode utang usaha 33 hari. Siklus konversi kas adalah...", "o": ["46 hari", "30 hari", "112 hari", "36 hari"], "a": 0},
    {"q": "Periode persediaan 51 hari, periode penagihan piutang 20 hari, periode utang usaha 16 hari. Siklus konversi kas adalah...", "o": ["-15 hari", "55 hari", "47 hari", "87 hari"], "a": 1},
    {"q": "Periode persediaan 72 hari, periode penagihan piutang 37 hari, periode utang usaha 25 hari. Siklus konversi kas adalah...", "o": ["60 hari", "134 hari", "-10 hari", "84 hari"], "a": 3},
    {"q": "Periode persediaan 62 hari, periode penagihan piutang 37 hari, periode utang usaha 34 hari. Siklus konversi kas adalah...", "o": ["133 hari", "9 hari", "65 hari", "59 hari"], "a": 2},
    {"q": "Periode persediaan 64 hari, periode penagihan piutang 20 hari, periode utang usaha 18 hari. Siklus konversi kas adalah...", "o": ["62 hari", "66 hari", "-26 hari", "102 hari"], "a": 1},
    {"q": "Periode persediaan 90 hari, periode penagihan piutang 49 hari, periode utang usaha 21 hari. Siklus konversi kas adalah...", "o": ["118 hari", "-20 hari", "62 hari", "160 hari"], "a": 0},
    {"q": "Periode persediaan 35 hari, periode penagihan piutang 56 hari, periode utang usaha 28 hari. Siklus konversi kas adalah...", "o": ["49 hari", "7 hari", "63 hari", "119 hari"], "a": 2},
    {"q": "Periode persediaan 47 hari, periode penagihan piutang 46 hari, periode utang usaha 16 hari. Siklus konversi kas adalah...", "o": ["15 hari", "77 hari", "17 hari", "109 hari"], "a": 1},
    {"q": "Periode persediaan 90 hari, periode penagihan piutang 50 hari, periode utang usaha 36 hari. Siklus konversi kas adalah...", "o": ["104 hari", "-4 hari", "176 hari", "76 hari"], "a": 0},
    {"q": "Periode persediaan 50 hari, periode penagihan piutang 58 hari, periode utang usaha 30 hari. Siklus konversi kas adalah...", "o": ["78 hari", "38 hari", "138 hari", "22 hari"], "a": 0},
    {"q": "Periode persediaan 83 hari, periode penagihan piutang 36 hari, periode utang usaha 16 hari. Siklus konversi kas adalah...", "o": ["135 hari", "63 hari", "103 hari", "-31 hari"], "a": 2},
    {"q": "Periode persediaan 60 hari, periode penagihan piutang 43 hari, periode utang usaha 23 hari. Siklus konversi kas adalah...", "o": ["40 hari", "126 hari", "80 hari", "6 hari"], "a": 2},
    {"q": "Periode persediaan 47 hari, periode penagihan piutang 52 hari, periode utang usaha 41 hari. Siklus konversi kas adalah...", "o": ["36 hari", "58 hari", "140 hari", "46 hari"], "a": 1},
    {"q": "Periode persediaan 67 hari, periode penagihan piutang 23 hari, periode utang usaha 41 hari. Siklus konversi kas adalah...", "o": ["85 hari", "131 hari", "49 hari", "-3 hari"], "a": 2},
    {"q": "Dividen tahun depan Rp250 per saham, tingkat imbal hasil diharapkan 12 persen, pertumbuhan dividen 6 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp4166.67", "Rp3333.33", "Rp1388.89", "Rp15"], "a": 0},
    {"q": "Dividen tahun depan Rp200 per saham, tingkat imbal hasil diharapkan 15 persen, pertumbuhan dividen 4 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp1052.63", "Rp1454.55", "Rp22", "Rp1818.18"], "a": 3},
    {"q": "Dividen tahun depan Rp200 per saham, tingkat imbal hasil diharapkan 16 persen, pertumbuhan dividen 6 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp909.09", "Rp1600", "Rp20", "Rp2000"], "a": 3},
    {"q": "Dividen tahun depan Rp100 per saham, tingkat imbal hasil diharapkan 16 persen, pertumbuhan dividen 4 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp12", "Rp833.33", "Rp666.67", "Rp500"], "a": 1},
    {"q": "Dividen tahun depan Rp300 per saham, tingkat imbal hasil diharapkan 14 persen, pertumbuhan dividen 5 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp27", "Rp1578.95", "Rp3333.33", "Rp2666.67"], "a": 2},
    {"q": "Dividen tahun depan Rp150 per saham, tingkat imbal hasil diharapkan 14 persen, pertumbuhan dividen 6 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp750", "Rp1500", "Rp12", "Rp1875"], "a": 3},
    {"q": "Dividen tahun depan Rp150 per saham, tingkat imbal hasil diharapkan 16 persen, pertumbuhan dividen 4 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp1000", "Rp1250", "Rp18", "Rp750"], "a": 1},
    {"q": "Dividen tahun depan Rp150 per saham, tingkat imbal hasil diharapkan 14 persen, pertumbuhan dividen 5 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp789.47", "Rp1666.67", "Rp13.5", "Rp1333.33"], "a": 1},
    {"q": "Dividen tahun depan Rp200 per saham, tingkat imbal hasil diharapkan 14 persen, pertumbuhan dividen 6 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp1000", "Rp2500", "Rp2000", "Rp16"], "a": 1},
    {"q": "Dividen tahun depan Rp250 per saham, tingkat imbal hasil diharapkan 16 persen, pertumbuhan dividen 4 persen. Dengan model Gordon, harga wajar saham adalah...", "o": ["Rp1250", "Rp1666.67", "Rp2083.33", "Rp30"], "a": 2},
    {"q": "Sebuah obligasi membayar kupon Rp110 per tahun dan harga pasarnya Rp780. Current yield obligasi tersebut adalah...", "o": ["16.1 persen", "7.09 persen", "12.6 persen", "14.1 persen"], "a": 3},
    {"q": "Sebuah obligasi membayar kupon Rp130 per tahun dan harga pasarnya Rp1100. Current yield obligasi tersebut adalah...", "o": ["10.32 persen", "11.82 persen", "8.46 persen", "13.82 persen"], "a": 1},
    {"q": "Sebuah obligasi membayar kupon Rp80 per tahun dan harga pasarnya Rp980. Current yield obligasi tersebut adalah...", "o": ["10.16 persen", "6.66 persen", "8.16 persen", "12.25 persen"], "a": 2},
    {"q": "Sebuah obligasi membayar kupon Rp140 per tahun dan harga pasarnya Rp920. Current yield obligasi tersebut adalah...", "o": ["13.72 persen", "17.22 persen", "15.22 persen", "6.57 persen"], "a": 2},
    {"q": "Sebuah obligasi membayar kupon Rp85 per tahun dan harga pasarnya Rp1020. Current yield obligasi tersebut adalah...", "o": ["10.33 persen", "12 persen", "8.33 persen", "6.83 persen"], "a": 2},
    {"q": "Sebuah obligasi membayar kupon Rp110 per tahun dan harga pasarnya Rp1100. Current yield obligasi tersebut adalah...", "o": ["10 persen ", "10 persen", "8.5 persen", "12 persen"], "a": 1},
    {"q": "Sebuah obligasi membayar kupon Rp90 per tahun dan harga pasarnya Rp1020. Current yield obligasi tersebut adalah...", "o": ["8.82 persen", "11.33 persen", "10.82 persen", "7.32 persen"], "a": 0},
    {"q": "Sebuah obligasi membayar kupon Rp75 per tahun dan harga pasarnya Rp1150. Current yield obligasi tersebut adalah...", "o": ["5.02 persen", "6.52 persen", "8.52 persen", "15.33 persen"], "a": 1},
    {"q": "Sebuah obligasi membayar kupon Rp75 per tahun dan harga pasarnya Rp1080. Current yield obligasi tersebut adalah...", "o": ["8.94 persen", "5.44 persen", "14.4 persen", "6.94 persen"], "a": 3},
    {"q": "Sebuah obligasi membayar kupon Rp75 per tahun dan harga pasarnya Rp820. Current yield obligasi tersebut adalah...", "o": ["9.15 persen", "7.65 persen", "11.15 persen", "10.93 persen"], "a": 0},
    {"q": "Sebuah obligasi membayar kupon Rp85 per tahun dan harga pasarnya Rp1150. Current yield obligasi tersebut adalah...", "o": ["13.53 persen", "9.39 persen", "7.39 persen", "5.89 persen"], "a": 2},
    {"q": "Sebuah obligasi membayar kupon Rp140 per tahun dan harga pasarnya Rp1150. Current yield obligasi tersebut adalah...", "o": ["12.17 persen", "10.67 persen", "8.21 persen", "14.17 persen"], "a": 0},
    {"q": "Sebuah obligasi membayar kupon Rp100 per tahun dan harga pasarnya Rp780. Current yield obligasi tersebut adalah...", "o": ["12.82 persen", "7.8 persen", "14.82 persen", "11.32 persen"], "a": 0},
    {"q": "Sebuah obligasi membayar kupon Rp90 per tahun dan harga pasarnya Rp1100. Current yield obligasi tersebut adalah...", "o": ["6.68 persen", "8.18 persen", "12.22 persen", "10.18 persen"], "a": 1},
    {"q": "Sebuah obligasi membayar kupon Rp95 per tahun dan harga pasarnya Rp950. Current yield obligasi tersebut adalah...", "o": ["10 persen ", "10 persen", "12 persen", "8.5 persen"], "a": 1},
    {"q": "Sebuah obligasi membayar kupon Rp150 per tahun dan harga pasarnya Rp1020. Current yield obligasi tersebut adalah...", "o": ["13.21 persen", "14.71 persen", "6.8 persen", "16.71 persen"], "a": 1},
]

assert len(UAS_BANK) == 200, f"Bank soal harus 200, saat ini {len(UAS_BANK)}"
